"""Idiomatic Python facade over the generated ``zerofs_ffi`` bindings.

Import this module (``import zerofs_client``) instead of the raw ``zerofs_ffi``: it
re-exports everything generated by uniffi and layers the Python niceties uniffi
cannot generate itself: async context managers, async iteration, streaming,
``PathLike`` arguments, string path helpers, and a blocking (sync) API.

```python
import zerofs_client

async with await zerofs_client.Client.connect("unix:/run/zerofs/9p.sock") as fs:
    await fs.write("/hello.txt", b"hi")
    async with await fs.open_dir("/") as d:
        async for entry in d:                 # streams the directory in batches
            print(entry.name)

# Or, from synchronous code:
with zerofs_client.connect_sync("unix:/run/zerofs/9p.sock") as fs:
    print(fs.read("/hello.txt"))
```

The generated low-level module stays available as ``zerofs_ffi``.
"""

from __future__ import annotations

import asyncio
import os
import threading
import types
import typing
import weakref
from typing import Any, AsyncIterable, AsyncIterator, Awaitable, Iterator, Optional, TypeVar, Union

from ._zerofs_ffi import *  # noqa: F401,F403  (re-export records, enums, errors)
from . import _zerofs_ffi as _ffi

if typing.TYPE_CHECKING:
    StrPath = Union[str, "os.PathLike[str]"]
    _Handle = Union[_ffi.Client, _ffi.File, _ffi.Dir]
    _T = TypeVar("_T")


# `async with await Client.connect(...) as fs:` closes the handle on exit.

async def _aenter(self: _Handle) -> _Handle:
    return self


async def _aexit(
    self: _Handle,
    _exc_type: Optional[type[BaseException]],
    _exc: Optional[BaseException],
    _tb: Optional[types.TracebackType],
) -> bool:
    await self.close()
    return False


for _cls in (_ffi.Client, _ffi.File, _ffi.Dir):
    _cls.__aenter__ = _aenter
    _cls.__aexit__ = _aexit


async def _dir_aiter(self: _ffi.Dir) -> AsyncIterator[_ffi.DirEntry]:
    while True:
        batch = await self.next_batch(None)
        if not batch:
            return
        for entry in batch:
            yield entry


_ffi.Dir.__aiter__ = _dir_aiter


async def _file_read_chunks(self: _ffi.File, chunk_size: int = 1 << 20) -> AsyncIterator[bytes]:
    """Yield the file's contents in ``chunk_size`` byte chunks (from offset 0)."""
    offset = 0
    while True:
        chunk = await self.read_at(offset, chunk_size)
        if not chunk:
            return
        offset += len(chunk)
        yield chunk


_ffi.File.read_chunks = _file_read_chunks


async def _file_write_from(
    self: _ffi.File, chunks: AsyncIterable[bytes], offset: int = 0
) -> int:
    """Write ``chunks`` from an async iterable at increasing offsets from ``offset``.

    Returns the total number of bytes written. Empty chunks are skipped.
    """
    written = 0
    async for chunk in chunks:
        if not chunk:
            continue
        await self.write_at(offset + written, chunk)
        written += len(chunk)
    return written


_ffi.File.write_from = _file_write_from


# Convenience accessors mirroring the Rust client, so callers write
# meta.is_dir() instead of meta.file_type == zerofs_client.FileType.DIR.

def _meta_is_file(self: _ffi.Metadata) -> bool:
    return self.file_type == _ffi.FileType.FILE


def _meta_is_dir(self: _ffi.Metadata) -> bool:
    return self.file_type == _ffi.FileType.DIR


def _meta_is_symlink(self: _ffi.Metadata) -> bool:
    return self.file_type == _ffi.FileType.SYMLINK


def _meta_permissions(self: _ffi.Metadata) -> int:
    """Permission bits only (mode & 0o7777)."""
    return self.mode & 0o7777


_ffi.Metadata.is_file = _meta_is_file
_ffi.Metadata.is_dir = _meta_is_dir
_ffi.Metadata.is_symlink = _meta_is_symlink
_ffi.Metadata.permissions = _meta_permissions


async def _read_text(self: _ffi.Client, path: StrPath, encoding: str = "utf-8") -> str:
    return (await self.read(path)).decode(encoding)


async def _write_text(self: _ffi.Client, path: StrPath, text: str, encoding: str = "utf-8") -> None:
    await self.write(path, text.encode(encoding))


_ffi.Client.read_text = _read_text
_ffi.Client.write_text = _write_text


# uniffi path parameters are `str`; accept `os.PathLike` (e.g. `pathlib.Path`)
# transparently by `os.fspath`-ing the path positions of each path-taking method.

def _fspath(value: Any) -> Any:
    return os.fspath(value) if isinstance(value, os.PathLike) else value


def _accept_pathlike(cls: type, name: str, positions: tuple[int, ...]) -> None:
    original = getattr(cls, name)

    async def wrapper(self: Any, *args: Any, **kwargs: Any) -> Any:
        args = list(args)
        for i in positions:
            if i < len(args):
                args[i] = _fspath(args[i])
        return await original(self, *args, **kwargs)

    wrapper.__name__ = name
    wrapper.__doc__ = original.__doc__
    setattr(cls, name, wrapper)


# method name -> positional indices that carry a path
_PATH_ARGS: dict[str, tuple[int, ...]] = {
    "read": (0,), "read_range": (0,), "write": (0,), "append": (0,),
    "stat": (0,), "metadata": (0,), "canonicalize": (0,), "exists": (0,),
    "set_attr": (0,), "chmod": (0,), "chown": (0,), "truncate": (0,),
    "set_times": (0,), "create_dir": (0,), "create_dir_all": (0,),
    "remove_file": (0,), "remove_dir": (0,), "remove_dir_all": (0,),
    "read_dir": (0,), "open_dir": (0,), "open": (0,), "create": (0,),
    "read_link": (0,), "mknod": (0,),
    "rename": (0, 1), "hard_link": (0, 1), "symlink": (0, 1),
}
for _name, _positions in _PATH_ARGS.items():
    _accept_pathlike(_ffi.Client, _name, _positions)


# `canonicalize`/`read_link` return raw bytes (lossless). These decode to `str`
# for the common UTF-8 case (`os.fsdecode`, surrogateescape for odd bytes).

async def _canonicalize_str(self: _ffi.Client, path: StrPath) -> str:
    return os.fsdecode(await self.canonicalize(path))


async def _read_link_str(self: _ffi.Client, path: StrPath) -> str:
    return os.fsdecode(await self.read_link(path))


_ffi.Client.canonicalize_str = _canonicalize_str
_ffi.Client.read_link_str = _read_link_str


# `connect_sync(...)` runs the async client on a private event loop in a
# background thread and returns a handle whose methods block. Returned
# `File`/`Dir` handles are wrapped the same way. Use it from non-async code.

def _stop_loop(loop: asyncio.AbstractEventLoop) -> None:
    loop.call_soon_threadsafe(loop.stop)


class _BackgroundLoop:
    def __init__(self) -> None:
        self._loop = asyncio.new_event_loop()
        self._thread = threading.Thread(target=self._loop.run_forever, daemon=True)
        self._thread.start()
        # Stop the loop (so its thread exits) when this object is collected, so a
        # never-closed SyncHandle does not leak its thread. stop() runs the same
        # finalizer, which fires at most once whether called or GC-triggered.
        self._finalize = weakref.finalize(self, _stop_loop, self._loop)

    def run(self, coro: Awaitable[_T]) -> _T:
        # Queue onto the loop and block for the result. The loop is kept alive by
        # its finalizer for as long as any SyncHandle sharing it is reachable, so
        # a call here always lands on a running loop (no stopped-loop deadlock).
        return asyncio.run_coroutine_threadsafe(coro, self._loop).result()

    def stop(self) -> None:
        self._finalize()


class SyncHandle:
    """Blocking wrapper around an async `Client`/`File`/`Dir`."""

    def __init__(self, inner: _Handle, loop: _BackgroundLoop) -> None:
        object.__setattr__(self, "_inner", inner)
        object.__setattr__(self, "_loop", loop)

    def __getattr__(self, name: str) -> Any:
        attr = getattr(self._inner, name)
        if not callable(attr):
            return attr

        def call(*args: Any, **kwargs: Any) -> Any:
            result = attr(*args, **kwargs)
            if asyncio.iscoroutine(result):
                result = self._loop.run(result)
            if isinstance(result, (_ffi.Client, _ffi.File, _ffi.Dir)):
                return SyncHandle(result, self._loop)
            return result

        return call

    def __enter__(self) -> SyncHandle:
        return self

    def __exit__(
        self,
        _exc_type: Optional[type[BaseException]],
        _exc: Optional[BaseException],
        _tb: Optional[types.TracebackType],
    ) -> bool:
        # Close the handle; the shared background loop is torn down by its
        # finalizer once this handle and every child sharing it are gone, so we
        # must not stop it here while a child handle may still be in use.
        self.close()
        return False

    def __iter__(self) -> Iterator[_ffi.DirEntry]:
        while True:
            batch = self.next_batch(None)
            if not batch:
                return
            yield from batch


def connect_sync(target: str) -> SyncHandle:
    """Connect and return a blocking [`SyncHandle`] over a background loop."""
    loop = _BackgroundLoop()
    try:
        client = loop.run(_ffi.Client.connect(target))
    except BaseException:
        loop.stop()  # connect failed: tear the loop down instead of leaking it
        raise
    return SyncHandle(client, loop)
