

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CLONE_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CLONE_CLIENT
uint64_t uniffi_zerofs_ffi_fn_clone_client(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FREE_CLIENT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FREE_CLIENT
void uniffi_zerofs_ffi_fn_free_client(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CONSTRUCTOR_CLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CONSTRUCTOR_CLIENT_CONNECT
uint64_t uniffi_zerofs_ffi_fn_constructor_client_connect(RustBuffer target
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CONSTRUCTOR_CLIENT_CONNECT_WITH
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CONSTRUCTOR_CLIENT_CONNECT_WITH
uint64_t uniffi_zerofs_ffi_fn_constructor_client_connect_with(RustBuffer target, RustBuffer opts
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_APPEND
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_APPEND
uint64_t uniffi_zerofs_ffi_fn_method_client_append(uint64_t ptr, RustBuffer path, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CANONICALIZE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CANONICALIZE
uint64_t uniffi_zerofs_ffi_fn_method_client_canonicalize(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CAPABILITIES
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CAPABILITIES
RustBuffer uniffi_zerofs_ffi_fn_method_client_capabilities(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CHMOD
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CHMOD
uint64_t uniffi_zerofs_ffi_fn_method_client_chmod(uint64_t ptr, RustBuffer path, uint32_t mode
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CHOWN
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CHOWN
uint64_t uniffi_zerofs_ffi_fn_method_client_chown(uint64_t ptr, RustBuffer path, RustBuffer uid, RustBuffer gid
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CLOSE
uint64_t uniffi_zerofs_ffi_fn_method_client_close(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CREATE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CREATE
uint64_t uniffi_zerofs_ffi_fn_method_client_create(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CREATE_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CREATE_DIR
uint64_t uniffi_zerofs_ffi_fn_method_client_create_dir(uint64_t ptr, RustBuffer path, uint32_t mode
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CREATE_DIR_ALL
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_CREATE_DIR_ALL
uint64_t uniffi_zerofs_ffi_fn_method_client_create_dir_all(uint64_t ptr, RustBuffer path, uint32_t mode
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_EXISTS
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_EXISTS
uint64_t uniffi_zerofs_ffi_fn_method_client_exists(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_HARD_LINK
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_HARD_LINK
uint64_t uniffi_zerofs_ffi_fn_method_client_hard_link(uint64_t ptr, RustBuffer original, RustBuffer link
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_METADATA
uint64_t uniffi_zerofs_ffi_fn_method_client_metadata(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_MKNOD
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_MKNOD
uint64_t uniffi_zerofs_ffi_fn_method_client_mknod(uint64_t ptr, RustBuffer path, RustBuffer kind, uint32_t mode
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_OPEN
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_OPEN
uint64_t uniffi_zerofs_ffi_fn_method_client_open(uint64_t ptr, RustBuffer path, RustBuffer opts
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_OPEN_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_OPEN_DIR
uint64_t uniffi_zerofs_ffi_fn_method_client_open_dir(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ
uint64_t uniffi_zerofs_ffi_fn_method_client_read(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ_DIR
uint64_t uniffi_zerofs_ffi_fn_method_client_read_dir(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ_LINK
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ_LINK
uint64_t uniffi_zerofs_ffi_fn_method_client_read_link(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ_RANGE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_READ_RANGE
uint64_t uniffi_zerofs_ffi_fn_method_client_read_range(uint64_t ptr, RustBuffer path, uint64_t offset, uint32_t len
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_REMOVE_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_REMOVE_DIR
uint64_t uniffi_zerofs_ffi_fn_method_client_remove_dir(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_REMOVE_DIR_ALL
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_REMOVE_DIR_ALL
uint64_t uniffi_zerofs_ffi_fn_method_client_remove_dir_all(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_REMOVE_FILE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_REMOVE_FILE
uint64_t uniffi_zerofs_ffi_fn_method_client_remove_file(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_RENAME
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_RENAME
uint64_t uniffi_zerofs_ffi_fn_method_client_rename(uint64_t ptr, RustBuffer from, RustBuffer to
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SET_ATTR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SET_ATTR
uint64_t uniffi_zerofs_ffi_fn_method_client_set_attr(uint64_t ptr, RustBuffer path, RustBuffer attrs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SET_TIMES
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SET_TIMES
uint64_t uniffi_zerofs_ffi_fn_method_client_set_times(uint64_t ptr, RustBuffer path, RustBuffer atime, RustBuffer mtime
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_STAT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_STAT
uint64_t uniffi_zerofs_ffi_fn_method_client_stat(uint64_t ptr, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_STATFS
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_STATFS
uint64_t uniffi_zerofs_ffi_fn_method_client_statfs(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SYMLINK
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SYMLINK
uint64_t uniffi_zerofs_ffi_fn_method_client_symlink(uint64_t ptr, RustBuffer target, RustBuffer link_path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SYNC
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_SYNC
uint64_t uniffi_zerofs_ffi_fn_method_client_sync(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_TRUNCATE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_TRUNCATE
uint64_t uniffi_zerofs_ffi_fn_method_client_truncate(uint64_t ptr, RustBuffer path, uint64_t size
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_WRITE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_CLIENT_WRITE
uint64_t uniffi_zerofs_ffi_fn_method_client_write(uint64_t ptr, RustBuffer path, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CLONE_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CLONE_DIR
uint64_t uniffi_zerofs_ffi_fn_clone_dir(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FREE_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FREE_DIR
void uniffi_zerofs_ffi_fn_free_dir(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_CLOSE
uint64_t uniffi_zerofs_ffi_fn_method_dir_close(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_CREATE_DIR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_CREATE_DIR_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_create_dir_at(uint64_t ptr, RustBuffer name, uint32_t mode
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_LINK_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_LINK_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_link_at(uint64_t ptr, uint64_t original_dir, RustBuffer original_name, RustBuffer new_name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_METADATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_METADATA
uint64_t uniffi_zerofs_ffi_fn_method_dir_metadata(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_METADATA_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_METADATA_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_metadata_at(uint64_t ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_MKNOD_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_MKNOD_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_mknod_at(uint64_t ptr, RustBuffer name, RustBuffer kind, uint32_t mode
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_NEXT_BATCH
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_NEXT_BATCH
uint64_t uniffi_zerofs_ffi_fn_method_dir_next_batch(uint64_t ptr, RustBuffer max_entries
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_OPEN_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_OPEN_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_open_at(uint64_t ptr, RustBuffer name, RustBuffer opts
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_OPEN_DIR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_OPEN_DIR_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_open_dir_at(uint64_t ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_READ_LINK_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_READ_LINK_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_read_link_at(uint64_t ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_REMOVE_DIR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_REMOVE_DIR_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_remove_dir_at(uint64_t ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_REMOVE_FILE_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_REMOVE_FILE_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_remove_file_at(uint64_t ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_RENAME_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_RENAME_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_rename_at(uint64_t ptr, RustBuffer old_name, uint64_t new_dir, RustBuffer new_name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_REWIND
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_REWIND
uint64_t uniffi_zerofs_ffi_fn_method_dir_rewind(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_SET_ATTR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_SET_ATTR
uint64_t uniffi_zerofs_ffi_fn_method_dir_set_attr(uint64_t ptr, RustBuffer attrs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_SET_ATTR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_SET_ATTR_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_set_attr_at(uint64_t ptr, RustBuffer name, RustBuffer attrs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_SYMLINK_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_DIR_SYMLINK_AT
uint64_t uniffi_zerofs_ffi_fn_method_dir_symlink_at(uint64_t ptr, RustBuffer name, RustBuffer target
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CLONE_FILE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_CLONE_FILE
uint64_t uniffi_zerofs_ffi_fn_clone_file(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FREE_FILE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FREE_FILE
void uniffi_zerofs_ffi_fn_free_file(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_CLOSE
uint64_t uniffi_zerofs_ffi_fn_method_file_close(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_METADATA
uint64_t uniffi_zerofs_ffi_fn_method_file_metadata(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_READ_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_READ_AT
uint64_t uniffi_zerofs_ffi_fn_method_file_read_at(uint64_t ptr, uint64_t offset, uint32_t len
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SET_ATTR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SET_ATTR
uint64_t uniffi_zerofs_ffi_fn_method_file_set_attr(uint64_t ptr, RustBuffer attrs
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SET_LEN
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SET_LEN
uint64_t uniffi_zerofs_ffi_fn_method_file_set_len(uint64_t ptr, uint64_t size
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SYNC_ALL
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SYNC_ALL
uint64_t uniffi_zerofs_ffi_fn_method_file_sync_all(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SYNC_DATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_SYNC_DATA
uint64_t uniffi_zerofs_ffi_fn_method_file_sync_data(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_WRITE_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_METHOD_FILE_WRITE_AT
uint64_t uniffi_zerofs_ffi_fn_method_file_write_at(uint64_t ptr, uint64_t offset, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FUNC_ERROR_TO_ERRNO
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_FN_FUNC_ERROR_TO_ERRNO
int32_t uniffi_zerofs_ffi_fn_func_error_to_errno(RustBuffer error, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_zerofs_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_zerofs_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_FREE
void ffi_zerofs_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_zerofs_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U8
void ffi_zerofs_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U8
void ffi_zerofs_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U8
void ffi_zerofs_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_zerofs_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I8
void ffi_zerofs_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I8
void ffi_zerofs_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I8
void ffi_zerofs_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_zerofs_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U16
void ffi_zerofs_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U16
void ffi_zerofs_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U16
void ffi_zerofs_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_zerofs_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I16
void ffi_zerofs_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I16
void ffi_zerofs_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I16
void ffi_zerofs_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_zerofs_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U32
void ffi_zerofs_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U32
void ffi_zerofs_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U32
void ffi_zerofs_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_zerofs_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I32
void ffi_zerofs_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I32
void ffi_zerofs_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I32
void ffi_zerofs_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_zerofs_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_U64
void ffi_zerofs_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_U64
void ffi_zerofs_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_U64
void ffi_zerofs_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_zerofs_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_I64
void ffi_zerofs_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_I64
void ffi_zerofs_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_I64
void ffi_zerofs_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_zerofs_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_F32
void ffi_zerofs_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_F32
void ffi_zerofs_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_F32
void ffi_zerofs_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_zerofs_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_F64
void ffi_zerofs_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_F64
void ffi_zerofs_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_F64
void ffi_zerofs_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_zerofs_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_zerofs_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_zerofs_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_zerofs_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_zerofs_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_POLL_VOID
void ffi_zerofs_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_zerofs_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_FREE_VOID
void ffi_zerofs_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_zerofs_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_FUNC_ERROR_TO_ERRNO
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_FUNC_ERROR_TO_ERRNO
uint16_t uniffi_zerofs_ffi_checksum_func_error_to_errno(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_APPEND
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_APPEND
uint16_t uniffi_zerofs_ffi_checksum_method_client_append(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CANONICALIZE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CANONICALIZE
uint16_t uniffi_zerofs_ffi_checksum_method_client_canonicalize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CAPABILITIES
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CAPABILITIES
uint16_t uniffi_zerofs_ffi_checksum_method_client_capabilities(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CHMOD
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CHMOD
uint16_t uniffi_zerofs_ffi_checksum_method_client_chmod(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CHOWN
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CHOWN
uint16_t uniffi_zerofs_ffi_checksum_method_client_chown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CLOSE
uint16_t uniffi_zerofs_ffi_checksum_method_client_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CREATE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CREATE
uint16_t uniffi_zerofs_ffi_checksum_method_client_create(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CREATE_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CREATE_DIR
uint16_t uniffi_zerofs_ffi_checksum_method_client_create_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CREATE_DIR_ALL
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_CREATE_DIR_ALL
uint16_t uniffi_zerofs_ffi_checksum_method_client_create_dir_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_EXISTS
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_EXISTS
uint16_t uniffi_zerofs_ffi_checksum_method_client_exists(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_HARD_LINK
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_HARD_LINK
uint16_t uniffi_zerofs_ffi_checksum_method_client_hard_link(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_METADATA
uint16_t uniffi_zerofs_ffi_checksum_method_client_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_MKNOD
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_MKNOD
uint16_t uniffi_zerofs_ffi_checksum_method_client_mknod(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_OPEN
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_OPEN
uint16_t uniffi_zerofs_ffi_checksum_method_client_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_OPEN_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_OPEN_DIR
uint16_t uniffi_zerofs_ffi_checksum_method_client_open_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ
uint16_t uniffi_zerofs_ffi_checksum_method_client_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ_DIR
uint16_t uniffi_zerofs_ffi_checksum_method_client_read_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ_LINK
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ_LINK
uint16_t uniffi_zerofs_ffi_checksum_method_client_read_link(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ_RANGE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_READ_RANGE
uint16_t uniffi_zerofs_ffi_checksum_method_client_read_range(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_REMOVE_DIR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_REMOVE_DIR
uint16_t uniffi_zerofs_ffi_checksum_method_client_remove_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_REMOVE_DIR_ALL
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_REMOVE_DIR_ALL
uint16_t uniffi_zerofs_ffi_checksum_method_client_remove_dir_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_REMOVE_FILE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_REMOVE_FILE
uint16_t uniffi_zerofs_ffi_checksum_method_client_remove_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_RENAME
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_RENAME
uint16_t uniffi_zerofs_ffi_checksum_method_client_rename(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SET_ATTR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SET_ATTR
uint16_t uniffi_zerofs_ffi_checksum_method_client_set_attr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SET_TIMES
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SET_TIMES
uint16_t uniffi_zerofs_ffi_checksum_method_client_set_times(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_STAT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_STAT
uint16_t uniffi_zerofs_ffi_checksum_method_client_stat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_STATFS
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_STATFS
uint16_t uniffi_zerofs_ffi_checksum_method_client_statfs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SYMLINK
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SYMLINK
uint16_t uniffi_zerofs_ffi_checksum_method_client_symlink(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SYNC
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_SYNC
uint16_t uniffi_zerofs_ffi_checksum_method_client_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_TRUNCATE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_TRUNCATE
uint16_t uniffi_zerofs_ffi_checksum_method_client_truncate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_WRITE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_CLIENT_WRITE
uint16_t uniffi_zerofs_ffi_checksum_method_client_write(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_CLOSE
uint16_t uniffi_zerofs_ffi_checksum_method_dir_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_CREATE_DIR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_CREATE_DIR_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_create_dir_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_LINK_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_LINK_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_link_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_METADATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_METADATA
uint16_t uniffi_zerofs_ffi_checksum_method_dir_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_METADATA_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_METADATA_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_metadata_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_MKNOD_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_MKNOD_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_mknod_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_NEXT_BATCH
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_NEXT_BATCH
uint16_t uniffi_zerofs_ffi_checksum_method_dir_next_batch(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_OPEN_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_OPEN_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_open_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_OPEN_DIR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_OPEN_DIR_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_open_dir_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_READ_LINK_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_READ_LINK_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_read_link_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_REMOVE_DIR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_REMOVE_DIR_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_remove_dir_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_REMOVE_FILE_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_REMOVE_FILE_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_remove_file_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_RENAME_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_RENAME_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_rename_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_REWIND
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_REWIND
uint16_t uniffi_zerofs_ffi_checksum_method_dir_rewind(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_SET_ATTR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_SET_ATTR
uint16_t uniffi_zerofs_ffi_checksum_method_dir_set_attr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_SET_ATTR_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_SET_ATTR_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_set_attr_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_SYMLINK_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_DIR_SYMLINK_AT
uint16_t uniffi_zerofs_ffi_checksum_method_dir_symlink_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_CLOSE
uint16_t uniffi_zerofs_ffi_checksum_method_file_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_METADATA
uint16_t uniffi_zerofs_ffi_checksum_method_file_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_READ_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_READ_AT
uint16_t uniffi_zerofs_ffi_checksum_method_file_read_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SET_ATTR
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SET_ATTR
uint16_t uniffi_zerofs_ffi_checksum_method_file_set_attr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SET_LEN
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SET_LEN
uint16_t uniffi_zerofs_ffi_checksum_method_file_set_len(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SYNC_ALL
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SYNC_ALL
uint16_t uniffi_zerofs_ffi_checksum_method_file_sync_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SYNC_DATA
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_SYNC_DATA
uint16_t uniffi_zerofs_ffi_checksum_method_file_sync_data(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_WRITE_AT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_METHOD_FILE_WRITE_AT
uint16_t uniffi_zerofs_ffi_checksum_method_file_write_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_CONSTRUCTOR_CLIENT_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_CONSTRUCTOR_CLIENT_CONNECT
uint16_t uniffi_zerofs_ffi_checksum_constructor_client_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_CONSTRUCTOR_CLIENT_CONNECT_WITH
#define UNIFFI_FFIDEF_UNIFFI_ZEROFS_FFI_CHECKSUM_CONSTRUCTOR_CLIENT_CONNECT_WITH
uint16_t uniffi_zerofs_ffi_checksum_constructor_client_connect_with(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ZEROFS_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ZEROFS_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_zerofs_ffi_uniffi_contract_version(void
    
);
#endif


void zerofs_ffi_uniffiFutureContinuationCallback(uint64_t, int8_t);
void zerofs_ffi_uniffiFreeGorutine(uint64_t);
